apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-slack-app
patches:
- path: domain.json
  target:
    kind: Ingress
    name: ingress
resources:
- ../../base
- namespace.yaml
images:
- name: sce06147/slack-app
  newTag: d4f4ddb00fe55097a33465544b2dd6ede8eb2973
