apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: slack-app
patches:
- path: domain.json
  target:
    kind: Ingress
    name: ingress
resources:
- ../../base
- namespace.yaml
